<?php

/**
 * Created by PhpStorm.
 * User: smile
 * Date: 16-9-21
 * Time: 上午11:15
 */
class Module extends \yii\base\Module
{
    public $controllerNamespace = 'app\modules\common\controllers';
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }
}